spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/productdb
    username: admin
    password: admin

  data:
    redis:
       host: localhost
       port: 6379

  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:schema.sql

cache:
  enabled: true